# -*- coding: utf-8 -*-
"""eksperimen_absa_ner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_tTuZoa_8bZPPhOS0CGznlyZvo9P5ym

# SOAL 2
## Preprocessing, Regex, Representasi Teks, dan Similarity

Notebook ini mengimplementasikan tahapan preprocessing teks, regular expression, representasi teks menggunakan Bag of Words (BoW), N-Gram, TF-IDF, serta pengukuran similarity sesuai instruksi UAS.
"""

import pandas as pd
import numpy as np

file_path = "hasil_scraper_ulasan_app_tiktok.csv.xlsx"

print(" memuat file dataset")

df = pd.read_excel(file_path)

print("File berhasil dimuat ke dalam sistem!")
print("-" * 50)

jumlah_baris, jumlah_kolom = df.shape
print(f"📊 Dimensi Dataset:")
print(f"    - Total baris data : {jumlah_baris} baris")
print(f"    - Total kolom data : {jumlah_kolom} kolom")
print("-" * 50)

print("📋 Kolom yang terdeteksi di dalam file:")
for i, col in enumerate(df.columns, 1):
    print(f"    {i}. Kolom: '{col}'")
print("-" * 50)

print("🔍 Memeriksa apakah ada data yang kosong (Null/NaN):")
data_kosong = df.isnull().sum()
for col in df.columns:
    print(f"    - Kolom '{col}' memiliki {data_kosong[col]} baris kosong.")
print("-" * 50)

print("📸 Menampilkan 5 sampel baris data teratas (Data Mentah):")
print(df.head(5))

"""### 2.1 Text Preprocessing

Tahapan ini meliputi case folding, cleaning, tokenization, normalisasi slang, stopword removal, dan stemming.
"""

import re

def pipeline_cleaning_regex(text):
    """
    Fungsi untuk melakukan Case Folding dan pembersihan teks menggunakan Regex.
    Tahapan ini memenuhi instruksi SOAL 02 komponen kelengkapan preprocessing.
    """
    if not isinstance(text, str):
        return ""

    text_lowercase = text.lower()

    text_clean_noise = re.sub(r'https?://\S+|www\.\S+', '', text_lowercase)
    text_clean_noise = re.sub(r'@[^\s]+', '', text_clean_noise)
    text_clean_noise = re.sub(r'[^a-zA-Z\s]', '', text_clean_noise)


    text_normalized_space = re.sub(r'\s+', ' ', text_clean_noise).strip()

    return text_normalized_space

print("🔄 Sedang menjalankan proses Case Folding dan Cleaning dengan Regex...")
df['Clean_Regex_Text'] = df['Review Text'].apply(pipeline_cleaning_regex)
print("✅ Proses Cleaning Regex selesai!")
print("-" * 50)


print("📋 Tabel Perbandingan Sebelum dan Sesudah Preprocessing Regex (Sampel 5 Baris):")
print(df[['Review Text', 'Clean_Regex_Text']].head(5))

"""### 2.2 Implementasi Regular Expression (Regex)"""

kamus_normalisasi = {
    "udah": "sudah",
    "udh": "sudah",
    "gk": "tidak",
    "ga": "tidak",
    "gak": "tidak",
    "lemot": "lambat",
    "ngeleg": "macet",
    "ngeleg banget": "sangat macet",
    "bgt": "sangat",
    "banget": "sangat",
    "updat": "perbarui",
    "update": "perbarui",
    "diampas": "dihapus"
}

def pipeline_normalisasi_slang(text):
    """
    Fungsi untuk memecah kalimat menjadi kata (tokenisasi awal)
    dan mengganti kata tidak baku menggunakan kamus_normalisasi.
    """
    if not isinstance(text, str):
        return ""

    words = text.split()

    normalized_words = [kamus_normalisasi[word] if word in kamus_normalisasi else word for word in words]

    return " ".join(normalized_words)

print("🔄 Sedang memproses normalisasi kata slang dan typo...")
df['Clean_Normalized_Text'] = df['Clean_Regex_Text'].apply(pipeline_normalisasi_slang)
print("✅ Proses Normalisasi Slang selesai!")
print("-" * 50)


print("📋 Tabel Perbandingan Alur Preprocessing (Sampel 5 Baris):")
print(df[['Review Text', 'Clean_Regex_Text', 'Clean_Normalized_Text']].head(5))

"""### 2.3 Normalisasi Slang Word"""

import numpy as np


def hitung_minimum_edit_distance(kata_asal, kata_tujuan):
    """
    Menghitung jumlah operasi minimal (insert, delete, substitute)
    untuk mengubah kata_asal menjadi kata_tujuan (Soal 02 Langkah 4).
    """
    m = len(kata_asal)
    n = len(kata_tujuan)

    matriks_dp = [[0] * (n + 1) for _ in range(m + 1)]


    for i in range(m + 1):
        matriks_dp[i][0] = i
    for j in range(n + 1):
        matriks_dp[0][j] = j

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if kata_asal[i-1] == kata_tujuan[j-1]:
                matriks_dp[i][j] = matriks_dp[i-1][j-1]
            else:
                matriks_dp[i][j] = 1 + min(
                    matriks_dp[i-1][j],
                    matriks_dp[i][j-1],
                    matriks_dp[i-1][j-1]
                )
    return matriks_dp[m][n]



def hitung_cosine_similarity_manual(vektor_a, vektor_b):
    """
    Menghitung kemiripan sudut arah antara dua vektor teks numerik.
    """
    perkalian_titik = np.dot(vektor_a, vektor_b)
    norma_a = np.linalg.norm(vektor_a)
    norma_b = np.linalg.norm(vektor_b)

    if norma_a == 0 or norma_b == 0:
        return 0.0
    return perkalian_titik / (norma_a * norma_b)


print("📝 BUKTI UJI COBA METRIK KEMIRIPAN:")
print("-" * 50)

slang_uji = "gk"
baku_uji = "tidak"
jarak_edit = hitung_minimum_edit_distance(slang_uji, baku_uji)
print(f"1. [Minimum Edit Distance Evaluation] ")
print(f"   - Kata Asal (Slang)   : '{slang_uji}'")
print(f"   - Kata Tujuan (Baku)  : '{baku_uji}'")
print(f"   - Hasil Jarak Operasi : {jarak_edit} langkah perubahan")
print("-" * 50)

ulasan_0 = df['Clean_Normalized_Text'].iloc[0]
ulasan_1 = df['Clean_Normalized_Text'].iloc[1]


kosakata = list(set(ulasan_0.split() + ulasan_1.split()))


vektor_0 = [ulasan_0.split().count(kata) for kata in kosakata]
vektor_1 = [ulasan_1.split().count(kata) for kata in kosakata]

nilai_sim = hitung_cosine_similarity_manual(vektor_0, vektor_1)
print(f"2. [Cosine Similarity Evaluation] ")
print(f"   - Ulasan Index 0 : '{ulasan_0}'")
print(f"   - Ulasan Index 1 : '{ulasan_1}'")
print(f"   - Nilai Kemiripan: {nilai_sim:.4f} (Rentang nilai 0 hingga 1)")
print("-" * 50)

"""### 2.4 Representasi Teks Menggunakan Bag of Words (BoW)

Tahap ini mengubah kumpulan teks hasil preprocessing menjadi representasi numerik menggunakan metode Bag of Words (BoW).
"""

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

print("🔄 Membuat representasi Bag of Words (BoW)...")

# Menggunakan hasil preprocessing yang sudah ada
corpus = df['Clean_Normalized_Text'].astype(str)

# Membuat BoW
bow_vectorizer = CountVectorizer()
X_bow = bow_vectorizer.fit_transform(corpus)

print("✅ Ukuran Sparse Matrix BoW:", X_bow.shape)
print("\nContoh Sparse Matrix:")
print(X_bow)

# Menampilkan sebagian hasil dalam bentuk tabel
bow_df = pd.DataFrame(
    X_bow.toarray(),
    columns=bow_vectorizer.get_feature_names_out()
)

print("\nRepresentasi Bag of Words (5 data pertama):")
display(bow_df.head())

"""### 2.5 Representasi Teks Menggunakan TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

print("🔄 Sedang menghitung pembobotan kata dengan TF-IDF...")

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df['Clean_Normalized_Text'].astype(str))

print("✅ Matriks TF-IDF Berhasil Terbentuk!")
print("-" * 50)

jumlah_dokumen, jumlah_fitur_kata = tfidf_matrix.shape
print(f"📊 Analisis Karakteristik Matriks (Sparse Representation):")
print(f"    - Jumlah Dokumen (Baris) : {jumlah_dokumen} ulasan")
print(f"    - Jumlah Kosakata Unik (Kolom Fitur) : {jumlah_fitur_kata} kata unik")
print("-" * 50)

fitur_kata = tfidf_vectorizer.get_feature_names_out()
print("📋 Contoh 15 fitur kata acak dalam kamus TF-IDF Proyekmu:")
print(fitur_kata[10:25] if len(fitur_kata) > 25 else fitur_kata)
print("-" * 50)

"""# SOAL 3
## Modeling Aspect-Based Sentiment Analysis (ABSA)

## 3.1 Analisis Distribusi Rating dan Pembentukan Label Sentimen

Tahap ini menganalisis distribusi rating pada dataset, kemudian memetakan setiap rating menjadi label sentimen (positif, netral, dan negatif) yang akan digunakan sebagai target pada proses pelatihan model klasifikasi.
"""

print("📊 Menghitung jumlah ulasan berdasarkan Rating (Bintang 1-5):")

rating_counts = df['Rating'].value_counts().sort_index()


for rating, count in rating_counts.items():
    persentase = (count / len(df)) * 100
    print(f"    - Rating {rating}⭐ : {count} ulasan ({persentase:.2f}%)")
print("-" * 50)
print("🔄 Membuat Aturan Pemetaan Rating ke Label Sentimen...")

def map_rating_to_sentiment(rating):
    if rating >= 4:
        return 'positif'
    elif rating == 3:
        return 'netral'
    else:
        return 'negatif'

df['Initial_Sentiment'] = df['Rating'].apply(map_rating_to_sentiment)

print("✅ Kolom 'Initial_Sentiment' berhasil dibuat!")
print("-" * 50)
print("⚖️ Komposisi Kelas Sentimen Awal (Untuk Analisis Overfitting/Underfitting):")
sentiment_counts = df['Initial_Sentiment'].value_counts()
for sentiment, count in sentiment_counts.items():
    print(f"    - Kelas [{sentiment.upper()}] : {count} data")
print("-" * 50)
print("📸 Sampel data setelah dipetakan ke Label Sentimen:")
print(df[['Rating', 'Initial_Sentiment', 'Review Text']].head(5))

"""### 3.2 Pelatihan, Evaluasi, dan Penyimpanan Model Naive Bayes

Pada tahap ini dilakukan pembagian data menjadi data latih dan data uji, pelatihan model Naive Bayes menggunakan fitur TF-IDF, evaluasi performa model menggunakan metrik klasifikasi, serta penyimpanan model dan TF-IDF Vectorizer dalam format `.joblib` untuk digunakan pada aplikasi.
"""

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix
import joblib
import os

print("🔄 Menyiapkan pembagian data (Data Split Training & Testing)...")

# Menentukan Fitur (X) dari matriks TF-IDF dan Target Label Sentimen (y)
X_data = tfidf_matrix
y_label = df['Initial_Sentiment']

# Melakukan Split Data (80% Training, 20% Testing) secara runtut
# STRATIFY digunakan agar proporsi kelas (Positif, Negatif, Netral) di data train dan test tetap seimbang!
X_train, X_test, y_train, y_test = train_test_split(
    X_data,
    y_label,
    test_size=0.2,
    random_state=42,
    stratify=y_label
)

print(f"✅ Pembagian data berhasil dilakukan:")
print(f"    - Jumlah Data Latih (Training Set) : {X_train.shape[0]} ulasan")
print(f"    - Jumlah Data Uji (Testing Set)   : {X_test.shape[0]} ulasan")
print("-" * 50)


#PROSES PELATIHAN MODEL (TRAINING PHASE)
print("🤖 Sedang melatih model Baseline Naive Bayes untuk Klasifikasi Sentimen...")
model_nb_absa = MultinomialNB()
model_nb_absa.fit(X_train, y_train)
print("✅ Model Naive Bayes berhasil dilatih!")
print("-" * 50)


# EVALUASI MODEL SECARA KUANTITATIF (SOAL 03 Langkah 4)
print("📊 Mengevaluasi model pada Data Uji (Testing Set):")
y_prediksi = model_nb_absa.predict(X_test)

# Menampilkan Classification Report (Accuracy, Precision, Recall, F1-Score)
print("\n[Classification Report]:")
print(classification_report(y_test, y_prediksi))

print("-" * 50)


# MENYIMPAN MODEL BINER UNTUK DISAMBUNGKAN KE STREAMLIT NANTI
print("💾 Menyimpan model dan vectorizer agar bisa dipakai langsung di Streamlit...")

# Membuat direktori 'models/' secara otomatis jika belum ada di sistem folder
os.makedirs('models', exist_ok=True)

# Simpan model Naive Bayes dan objek TF-IDF Vectorizer yang sudah fit
joblib.dump(model_nb_absa, 'models/absa_model.joblib')
joblib.dump(tfidf_vectorizer, 'models/absa_vectorizer.joblib')

print("✅ Berkas 'absa_model.joblib' & 'absa_vectorizer.joblib' aman di folder 'models/'!")
print("-" * 50)

"""### 3.3 Error Analysis Model ABSA

Tahap ini menganalisis hasil prediksi yang tidak sesuai dengan label aktual. Error analysis dilakukan dengan membandingkan label prediksi dan label sebenarnya, kemudian menampilkan beberapa contoh kesalahan klasifikasi sebagai bahan evaluasi performa model.
"""

# Mengambil teks asli dari data uji (Testing Set) berdasarkan indeksnya
X_test_indices = y_test.index
teks_asli_uji = df['Review Text'].loc[X_test_indices].values
teks_bersih_uji = df['Clean_Normalized_Text'].loc[X_test_indices].values

# Membuat DataFrame khusus untuk membandingkan prediksi vs aktual
df_evaluasi = pd.DataFrame({
    'Teks_Asli': teks_asli_uji,
    'Teks_Bersih': teks_bersih_uji,
    'Aktual': y_test.values,
    'Prediksi': y_prediksi
})

# Menyaring baris di mana prediksi model berbeda dengan label aktual (Salah Tebak)
df_salah_tebak = df_evaluasi[df_evaluasi['Aktual'] != df_evaluasi['Prediksi']]

print(f"🔍 Menemukan {len(df_salah_tebak)} kasus salah tebak dari 100 data uji.")
print("-" * 50)

# Menampilkan 5 contoh kesalahan teratas secara mendalam untuk laporan
print("📋 5 Contoh Kasus Salah Tebak Model Baseline (Bahan Laporan):")
print("-" * 50)

sampel_eror = df_salah_tebak.head(5)
for i, row in enumerate(sampel_eror.itertuples(), 1):
    print(f"Kasus Eror ke-{i}:")
    print(f"   💬 Teks Asli   : {row.Teks_Asli}")
    print(f"   🧼 Teks Bersih : {row.Teks_Bersih}")
    print(f"   🎯 Label Asli  : {row.Aktual.upper()}")
    print(f"   🤖 Prediksi NB : {row.Prediksi.upper()}")
    print("-" * 50)

"""### 3.4 Visualisasi Confusion Matrix

Tahap ini menampilkan Confusion Matrix untuk memvisualisasikan hasil klasifikasi model Naive Bayes. Visualisasi digunakan untuk melihat jumlah prediksi yang benar maupun salah pada setiap kelas sentimen.
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

print(" memproses visualisasi Confusion Matrix...")

df['Initial_Sentiment'] = df['Rating'].apply(lambda r: 'positif' if r >= 4 else ('netral' if r == 3 else 'negatif'))

vektor_tfidf_lokal = TfidfVectorizer()
X_matriks_lokal = vektor_tfidf_lokal.fit_transform(df['Clean_Normalized_Text'].astype(str))
y_label_lokal = df['Initial_Sentiment']
X_train_lkl, X_test_lkl, y_train_lkl, y_test_lkl = train_test_split(
    X_matriks_lokal, y_label_lokal, test_size=0.2, random_state=42, stratify=y_label_lokal
)

model_nb_lokal = MultinomialNB()
model_nb_lokal.fit(X_train_lkl, y_train_lkl)
y_prediksi_lokal = model_nb_lokal.predict(X_test_lkl)

print("\n SUCCESS! Variabel terdefinisi. Berikut Confusion Matrix Proyekmu:")
cm = confusion_matrix(y_test_lkl, y_prediksi_lokal, labels=['negatif', 'netral', 'positif'])

plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['negatif', 'netral', 'positif'],
            yticklabels=['negatif', 'netral', 'positif'])
plt.title('Confusion Matrix - Sentimen Ulasan TikTok (Naive Bayes)')
plt.ylabel('Label Aktual (Asli dari Dosen)')
plt.xlabel('Label Prediksi (Tebakan Model)')
plt.show()

"""# SOAL 4
## Named Entity Recognition (NER)

### 4.1 Pembentukan Dataset BIO Tagging

Tahap ini membentuk dataset berformat BIO (Begin, Inside, Outside) dengan memberikan label pada setiap token berdasarkan aturan (rule-based). Dataset BIO yang dihasilkan akan digunakan sebagai data latih pada proses Named Entity Recognition (NER).
"""

import pandas as pd
import os

print("🔄 Memulai proses konversi kalimat ke format Token-Level BIO Tagging...")

# Menentukan kumpulan kata kunci (Lexicon-Rule) yang didefinisikan sebagai entitas ASPECT
# Ini selaras dengan masalah teknis yang sering muncul di ulasan TikTok-mu
kata_kunci_aspek = {
    "masuk": "ASPECT",
    "daftar": "ASPECT",
    "bug": "ASPECT",
    "update": "ASPECT",
    "perbarui": "ASPECT",
    "jeda": "ASPECT",
    "live": "ASPECT",
    "berat": "ASPECT"
}

baris_bio_token = []

# Mengambil 100 sampel kalimat teratas (memenuhi syarat minimal 100-200 kalimat NER di soal)
sampel_kalimat_ner = df['Clean_Normalized_Text'].head(100).tolist()

for indeks_kalimat, kalimat in enumerate(sampel_kalimat_ner):
    if not isinstance(kalimat, str) or kalimat.strip() == "":
        continue

    # Memecah kalimat menjadi token kata secara runtut
    daftar_token = kalimat.split()

    for i, token in enumerate(daftar_token):
        label_tag = "O"  # Default tag adalah Outside (Bukan entitas)

        # Aturan Pencocokan Aturan (Rule-Based Matching):
        if token in kata_kunci_aspek:
            # Periksa apakah token sebelumnya juga entitas yang sama untuk menentukan B- atau I-
            if i > 0 and daftar_token[i-1] in kata_kunci_aspek:
                label_tag = "I-ASPECT" # Inside Aspect (Lanjutan entitas)
            else:
                label_tag = "B-ASPECT" # Begin Aspect (Awal entitas)

        # Menyimpan data token level beserta indeks kalimatnya
        baris_bio_token.append({
            "Sentence_Idx": f"Sentence_{indeks_kalimat}",
            "Token": token,
            "Tag": label_tag
        })

# Mengubah hasil penandaan menjadi DataFrame
df_ner_bio = pd.DataFrame(baris_bio_token)

print("✅ Proses Pelabelan BIO Tagging Selesai!")
print("-" * 50)

# EKSPOR KE DIRECTORY DATA/ SESUAI FORMAT PENGUMPULAN UAS
os.makedirs('data', exist_ok=True)
path_ekspor_tsv = 'data/ner_bio_dataset.tsv'
df_ner_bio.to_csv(path_ekspor_tsv, sep='\t', index=False)

print(f"💾 File berhasil disimpan di: '{path_ekspor_tsv}'")
print(f"📊 Total record token yang terbentuk: {len(df_ner_bio)} baris token.")
print("-" * 50)

# Menampilkan sampel 15 baris token teratas untuk memverifikasi struktur aturan B-I-O
print("📋 Sampel Struktur Token-Level BIO Annotation (Bahan Tabel Laporan):")
print(df_ner_bio.head(15))

try:
    import sklearn_crfsuite
except ImportError:
    !pip install sklearn-crfsuite

"""### 4.2 Pelatihan Model CRF

Pada tahap ini dilakukan ekstraksi fitur setiap token, pembagian data menjadi data latih dan data uji, pelatihan model Conditional Random Field (CRF), serta penyimpanan model hasil pelatihan dalam format `.joblib` untuk digunakan kembali pada aplikasi.
"""

def token2features(sent, i):
    word = sent[i]
    features = {
        'bias': 1.0,
        'word.lower()': word.lower(),
        'word[-3:]': word[-3:],
        'word[-2:]': word[-2:],
        'word.isdigit()': word.isdigit(),
    }
    if i > 0:
        word1 = sent[i-1]
        features.update({
            '-1:word.lower()': word1.lower(),
        })
    else:
        features['BOS'] = True

    if i < len(sent) - 1:
        word1 = sent[i+1]
        features.update({
            '+1:word.lower()': word1.lower(),
        })
    else:
        features['EOS'] = True

    return features

def sent2features(sent):
    return [token2features(sent, i) for i in range(len(sent))]

df_bio = pd.read_csv('data/ner_bio_dataset.tsv', sep='\t')

# Kelompokkan token dan tag (menggunakan include_groups=False untuk mematikan DeprecationWarning jika pakai Pandas v2.x)
agg_func = lambda s: [(w, t) for w, t in zip(s["Token"].astype(str).tolist(), s["Tag"].astype(str).tolist())]

try:
    grouped_sentences = df_bio.groupby("Sentence_Idx", group_keys=False).apply(agg_func).tolist()
except TypeError:
    grouped_sentences = df_bio.groupby("Sentence_Idx").apply(agg_func).tolist()

X = [sent2features([token[0] for token in kalimat]) for kalimat in grouped_sentences]
y = [[token[1] for token in kalimat] for kalimat in grouped_sentences]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# PROSES TRAINING MODEL CRF & EXPORT .JOBLIB
from sklearn_crfsuite import CRF
import joblib
import os

print(f"🔄 Sedang melatih model NER berbasis CRF dengan {len(X_train)} kalimat...")
model_crf = CRF(
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True
)

# Menjalankan fitting data
model_crf.fit(X_train, y_train)
print("✅ Pelatihan model CRF selesai!")

# Simpan hasil model biner
os.makedirs('models', exist_ok=True)
joblib.dump(model_crf, 'models/ner_crf_model.joblib')
print("💾 File 'models/ner_crf_model.joblib' sukses disimpan dan siap digunakan di Streamlit!")

"""### 4.3 Evaluasi dan Error Analysis Model CRF

Pada tahap ini dilakukan evaluasi performa model CRF menggunakan metrik Precision, Recall, dan F1-Score. Selain itu, dilakukan error analysis dengan membandingkan tag aktual dan tag prediksi untuk mengidentifikasi contoh kesalahan pelabelan entitas.
"""

from sklearn_crfsuite import metrics
import warnings

# Menghilangkan warning pembagian nol (UndefinedMetricWarning) agar output rapi
warnings.filterwarnings('ignore', category=UserWarning)

# Melakukan prediksi menggunakan model CRF pada data uji (X_test)
y_pred_crf = model_crf.predict(X_test)

# CETAK CLASSIFICATION REPORT (Metrik Presisi, Recall, F1-Score)
print("📊 ===========================================================")
print("   HASIL EVALUASI KUANTITATIF MODEL NER (CRF) - TOKENS LEVEL")
print("=============================================================")
print(metrics.flat_classification_report(
    y_test, y_pred_crf, labels=['B-ASPECT', 'I-ASPECT'], digits=4
))

# OTOMATISASI ERROR ANALYSIS (Mencari 5 Sampel Kesalahan Tagging)
print("\n🔍 ===========================================================")
print("   AUTOMATED ERROR ANALYSIS: 5 CONTOH SALAH TAGGING (CRF)")
print("=============================================================")

error_count = 0

for i in range(len(X_test)):
    # FIX: Mengambil langsung kata asli dari key 'word.lower()' tanpa indeks [0]
    sentence_words = [fitur['word.lower()'] for fitur in X_test[i]]
    aktual_tags = y_test[i]
    prediksi_tags = y_pred_crf[i]

    if aktual_tags != prediksi_tags:
        for j in range(len(aktual_tags)):
            if aktual_tags[j] != prediksi_tags[j]:
                error_count += 1
                print(f"Kasus Salah Ke-{error_count}:")
                print(f" 📝 Kata/Token : '{sentence_words[j]}'")
                print(f" 🎯 Tag Aktual : {aktual_tags[j]}")
                print(f" 🤖 Tag Prediksi: {prediksi_tags[j]}")
                print("-" * 45)
                break

        if error_count >= 5:
            break

if error_count == 0:
    print("✨ Sempurna! Tidak ditemukan kesalahan tagging pada data uji CRF.")

"""### 4.4 Implementasi Prediksi NER pada Kalimat Baru

Tahap ini menguji model CRF yang telah dilatih dengan memberikan sebuah kalimat baru sebagai input. Model kemudian melakukan prediksi label BIO pada setiap token untuk menunjukkan hasil ekstraksi entitas secara langsung.
"""

# Contoh visualisasi sederhana
ulasan_contoh = "aplikasi tiktok sering bug dan membuat jeda saat live"
tokens = ulasan_contoh.split()
features = [token2features(tokens, i) for i in range(len(tokens))]
prediksi_tags = model_crf.predict([features])[0]

print("📋 Hasil Visualisasi Ekstraksi Entitas NER:")
print("-" * 50)
for token, tag in zip(tokens, prediksi_tags):
    if tag != 'O':
        print(f"[{token}] -> 🔥 \033[91m{tag}\033[0m")
    else:
        print(f"{token} -> {tag}")